### ISSUE TITLE
Prevent dictionaries that do not have the em:type set correctly

### ISSUE THREAD

**Issue by andymckay** [mozilla/amo-validator#364]
As per mozilla/olympia#1093

**Comment by andymckay** [comment]
This is going to hit us again with the next release of Firefox, ideally we should fix this.

**Comment by EnTeQuAk** [comment]
I'll work on this today.

Basically we should validate that the `em_type` is 64 (dictionary) right? Anything else?

**Comment by wagnerand** [comment]
> Anything else?

Not in the scope of this bug.

Generally, we could check whether the add-on contains javascript or HTML files as dictionaries shouldn't, and whether there is a `dictionaries` folder.
A typical dictionary looks like https://addons.mozilla.org/en-US/firefox/files/browse/382127/

**Comment by EnTeQuAk** [comment]
Opened up a PR for this, @wagnerand we already validate the layout for dictionaries a bit in https://github.com/mozilla/amo-validator/blob/master/validator/testcases/packagelayout.py#L273 so it should be quite easy to add additional requirements.
