### ISSUE TITLE
Validator does not pick up the files

### ISSUE THREAD

**Issue by erosman** [mozilla/amo-validator#365]
Validator shows all ticked while addon has a JQuery and other files that should have been picked up by the validator as valid or not valid libraries, etc

I tested it 3 times before rejecting the addon.

https://addons.mozilla.org/en-US/editors/review/scopus-parser

**Comment by wagnerand** [comment]
The file in question contains a file named `jquery-2.1.4.min.js` that is much smaller than the original jQuery. It is entirely possible the minified code did not raise any warnings.
