### ISSUE TITLE
False Report:  iframe/browser missing 'type' attribute

### ISSUE THREAD

**Issue by erosman** [mozilla/amo-validator#366]
As per title:
`<iframe id="requestpolicy-requestLog-frame" type="chrome" flex="1"/>`

Example:
https://addons.mozilla.org/en-US/firefox/files/compare/377109...369395/file/chrome/requestpolicy.jar/content/overlay.xul#top

**Comment by wagnerand** [comment]
I guess it is just a wrong validator warning message. We want the validator to flag iframes if they don't have `type="content"`.

It could say something like: "Dangerous or missing 'type' attribute".
