### ISSUE TITLE
Update of "Outdated version of Add-on SDK" notice

### ISSUE THREAD

**Issue by erosman** [mozilla/amo-validator#367]
At the moment the warning states:
> You are using version ******* of the Add-on SDK, which is outdated. Please upgrade to version 1.17 and repack your add-on

I personally alter it  (via a script) to state:
> You are using version ******* of the Add-on SDK, which is outdated. Please upgrade to version 1.17 or use JPM and repack your add-on.

The changes are **or use JPM** and a **full stop** at the end.

Update: Text updated subsequent to the comment by wagnerand

**Comment by wagnerand** [comment]
You cannot "upgrade" to JPM. It should be something like
```
You are using version ******* of the Add-on SDK, which is outdated. Please upgrade to version 1.17 or use JPM and repack your add-on.
```

**Comment by erosman** [comment]
Sounds good... I have changed my own version for now. :)

**Comment by wagnerand** [comment]
Actually changing this a little as we are no longer allowing the usage of cfx, and that warning only occurs for add-ons packed by cfx...PR coming...

**Comment by wagnerand** [comment]
Superseded by #379
