### ISSUE TITLE
False positive: createElement(NS)

### ISSUE THREAD

**Issue by Centril** [mozilla/amo-validator#368]
The code `doc.createElementNS( nsXUL, 'panelview' )` causes false positive...

The warning about `createElement` is a bug in the validator since the `<script>` tag is never used, and since `nsXUL` is a constant which can't be changed.

An example here: https://github.com/Centril/firefox-line/blob/master/src/search-engine.js#L206

**Comment by EnTeQuAk** [comment]
I could not reproduce this anymore, added a test to the validator that verifies that the code you referenced does not throw a false positive.

If the problem isn't fixed please feel free to comment and reopen.
