### ISSUE TITLE
Validator is missing issues

### ISSUE THREAD

**Issue by erosman** [mozilla/amo-validator#370]
Today I noticed that the validator is missing some issues ie: **nsIProcess** on this addon:
https://addons.mozilla.org/en-US/editors/review/fotideptsclient-addon

**Comment by wagnerand** [comment]
Closing as that add-on is no longer available.

**Comment by erosman** [comment]
Bug was posted over a month ago and only checked 5 days ago!

**Comment by erosman** [comment]
Here is another example:
https://addons.mozilla.org/en-US/editors/review/video-to-player

index.js#40
`var process = Cc["@mozilla.org/process/util;1"].createInstance(Ci.nsIProcess);`

I hope the issue gets fixed as closing unfixed issues can create problems.

**Comment by erosman** [comment]
Another example:
https://addons.mozilla.org/en-US/editors/review/quick-file-launcher

main.js#33
`var process = Cc["@mozilla.org/process/util;1"].createInstance(Ci.nsIProcess);`

**Comment by Noitidart** [comment]
Confirming. On quick file launcher, it is not showing the warning for nsIProcess. Used in main.js. But validator is not showing it.

**Comment by wagnerand** [comment]
This is because destructuring in `var {Cc, Ci} = require("chrome");` fails `Cc` and `Ci` to be detected as global variables. I'm not sure how to fix that, though.

**Comment by erosman** [comment]
It should be easy to detect. I do so with my own scripts and that is how I have picked up those (and others).

**Comment by wagnerand** [comment]
It's not that easy to detect with the current amo-validator structure as it
is not doing simple string or regex checks but actually analyzes the AST.

**Comment by erosman** [comment]
I haven't seen the code, so I can't comment properly. However, IMHO it is something that should be fixed especially if the auto-validating-signing depends on it.

**Comment by wagnerand** [comment]
Since https://blog.mozilla.org/addons/2015/12/01/de-coupling-reviews-from-signing-unlisted-add-ons/ we are no longer manually reviewing unlisted add-ons at all and all of them are auto-approved regardless of the warnings they raise.

**Comment by erosman** [comment]
Another example of 
https://addons.mozilla.org/en-US/developers/addon/guivers/file/502448/validation

Missing:
https://addons.mozilla.org/en-US/firefox/files/browse/502448/file/js/function.js#top
`var script = myIframe.contentWindow.document.createElement("script");`

**Comment by erosman** [comment]
There are a LOT that are missed in this validation. Please refer to the review
https://addons.mozilla.org/en-US/editors/review/donegood

**Comment by erosman** [comment]
`eval()` is missed here:
https://addons.mozilla.org/en-US/firefox/files/browse/544938/file/js/background.js#top

**Comment by wagnerand** [comment]
@erosman  Ugh, that's bad.

However, that add-on is a webextension, so you need to file this for the [addons-linter](https://github.com/mozilla/addons-linter).

**Comment by EnTeQuAk** [comment]
I am closing this for now, for several reasons:

* Most of the WebExtension issues mentioned here are solved or logged in separate issues
* The issue matching `nsIProcess` and with that destructured `{ Cc, Ci } = require('chrome')` is not doable in a reasonable amount of work with how amo-validator works these days

`nsIProcess` is matched and warnings will be properly issued if no namespace mangling happens.
