### ISSUE TITLE
Use Dispensary hashes instead of hashes built by the Python script

### ISSUE THREAD

**Issue by tofumatt** [mozilla/amo-validator#384]
This is a "nice-to-have" bug for someone to work on but no rush.

We now have a new JS library hash collector that should update to new versions of libraries at https://github.com/mozilla/dispensary. It keeps its own `hashes.txt` and could be used by this validator.

**Comment by wagnerand** [comment]
Since https://github.com/mozilla/addons-linter/issues/869 wants to move `dispensary` into `addons-linter` and `amo-validator` is going to be phased out, I don't think this is relevant anymore.

@tofumatt if you disagree, feel free to reopen.
