### ISSUE TITLE
Ignore sourceMappingURL when validate known versions

### ISSUE THREAD

**Issue by ArtemAvramenko** [mozilla/amo-validator#388]
E.g. jQuery from GitHub repository differs from jQuery on code.jquery.com:

https://github.com/jquery/jquery/blob/7751e69b615c6eca6f783a81e292a55725af6b85/dist/jquery.min.js
http://code.jquery.com/jquery-2.1.4.min.js

It contains line at the end:
`//# sourceMappingURL=jquery.min.map`

You can just skip empty or comment lines when calculate a content hash.

**Comment by wagnerand** [comment]
Currently, libraries are matched based on their file hash, so we don't actually compare the contents. #271 should change that behavior but given its age, it's unclear whether it will happen. I'm closing this one though as there is nothing else we can do.
