### ISSUE TITLE
Tab stops change not working

### ISSUE THREAD

**Issue by erosman** [mozilla/amo-validator#392]
It was a useful feature and it has been a while that Tab stops change is not working ie changing it has no effect at all.

**Comment by muffinresearch** [comment]
> It was a useful feature and it has been a while that Tab stops change is not working ie changing it has no effect at all.

Could you add clear steps to reproduce and describe the problem in more detail please?

**Comment by erosman** [comment]
For example on one of the following:
```
https://addons.mozilla.org/en-US/firefox/files/compare/398047...384466/
https://addons.mozilla.org/en-US/firefox/files/browse/398047/
```

On the left pane:
**Tab stops: 3 ↓ ↑**

Changing the above value (3) or clicking on either ↓ ↑ (which would change the value 3) would increase or deceases the number of leading space (ie indentation) eg:

```
var selector;
                 var selector;
                               var selector;
```

However, above hasn't been working for a while.
I hope that helps.

**Comment by andymckay** [comment]
If anyone is planning on fixing this, the code is in the addons-server repository.

**Comment by wagnerand** [comment]
Probably a regression from https://github.com/mozilla/addons-server/commit/ecadb47a7c9108d5aacb98084926157ab28166e0

**Comment by EnTeQuAk** [comment]
Closing in favor of https://github.com/mozilla/addons-server/issues/5969
