### ISSUE TITLE
Inconsistent priority for install.rdf vs manifest.json

### ISSUE THREAD

**Issue by bjornstar** [mozilla/amo-validator#405]
I have `manifest.json` for Chrome and `install.rdf` for Firefox and I got the following validation error.

<img width="733" alt="validation-error" src="https://cloud.githubusercontent.com/assets/20630/13544894/57654dd4-e2c0-11e5-9b77-80cb0b737163.png">

```
No Mozilla products listed as target applications
Error: None of the target applications listed in the manifest are supported Mozilla products. At least one official Mozilla product must be supported for inclusion on addons.mozilla.org.

See https://addons.mozilla.org/firefox/pages/appversions/ for more information on supported target applications on AMO.

manifest.json
```

In #386 support was added for manifest.json

In `amo-validator/tests/helper.py`:

```
        if 'install.rdf' in package:
            err.save_resource('has_install_rdf', True)
            rdf_data = package.read('install.rdf')
            install_rdf = RDFParser(err, rdf_data)
            err.save_resource('install_rdf', install_rdf)
        elif 'manifest.json' in package:
            err.save_resource('has_manifest_json', True)
            manifest_data = package.read('manifest.json')
            manifest_json = ManifestJsonParser(err, manifest_data)
            err.save_resource('install_rdf', manifest_json)
```

In `amo-validator/validator/testcases/targetapplication.py` the order is reversed:
```
    if manifest_json:
        applications = manifest_json.get_applications()
        manifest_file = 'manifest.json'
    elif install_rdf:
        applications = install_rdf.get_applications()
        manifest_file = 'install.rdf'
```

Which is the correct order? Does `install.rdf` take precedence over `manifest.json`? Are you going to validate both manifest files?

I will be adding an `applications` entry to my `manifest.json` (if chrome doesn't complain about it), but this inconsistency will cause problems for developers in the future.

**Comment by mstriemer** [comment]
It looks like [Firefox will read the `install.rdf`](https://dxr.mozilla.org/mozilla-central/rev/af7c0cb0798f5425d5d344cbaf0ac0ecb1a72a86/toolkit/mozapps/extensions/internal/XPIProvider.jsm#773) first but I'm not sure if this is the right code.

I'll confirm the ordering and then we can update one of these files accordingly.

**Comment by mstriemer** [comment]
@mossop it looks like the `install.rdf` is taking precedence over a `manifest.json` in Firefox, is that the case?

**Comment by Mossop** [comment]
Yes, per https://bugzilla.mozilla.org/show_bug.cgi?id=1196301

We hit exactly this case where some existing extensions already had a manifest.json present so we chose to avoid breaking those.

**Comment by bjornstar** [comment]
This bug is blocking me from updating my plugin:

<img width="377" alt="amo-failed-validation" src="https://cloud.githubusercontent.com/assets/20630/13726615/aa78bad4-e913-11e5-8d7a-617e8413b864.png">

I shouldn't need to modify `manifest.json` since I have `install.rdf`

**Comment by bjornstar** [comment]
Thank you! :D

**Comment by mstriemer** [comment]
Our next push is on Thursday at 9am pacific so this should be fixed then.
