### ISSUE TITLE
Dictionary with wrong "type" can be submitted

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/amo-validator#407]
Steps to reproduce:
1. Sign in to AMO-dev page https://addons-dev.allizom.org/en-US/
2. Submit a dictionary with a wrong "type" set (i.e. type=2)

Expected results:
The dictionary cannot be submitted because the "type" is wrong.

Actual results:
The dictionary can be submitted.

Notes/Issues:
Verified on AMO-dev FF45(Win 7).
Screenshot for this issue: 
![2016-03-11_1650](https://cloud.githubusercontent.com/assets/15685960/13705417/6bb9c272-e7a9-11e5-96b3-7947673a503e.png)

**Comment by ValentinaPC** [comment]
Not sure if the fix landed on AMO-dev FF45(Win 7), because I am still able to reproduce.
@muffinresearch ?

**Comment by wagnerand** [comment]
I just updated amo-validator, so the fix should be on AMO-dev now. Could you retry, please?

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF45(Win 7). Tried with type like "2", "4","8","32", "64", "128" and none.
Postfix screenshots: 
![2016-03-14_1541](https://cloud.githubusercontent.com/assets/15685960/13746532/8993de90-e9fc-11e5-859f-e18ad483633a.png)
![2016-03-14_1540](https://cloud.githubusercontent.com/assets/15685960/13746540/908f853c-e9fc-11e5-892b-9d6b4eca083f.png)
