### ISSUE TITLE
Upgrade simplejson to latest 3.8.1

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/amo-validator#415]
See https://github.com/mozilla/addons-server/pull/2357

**Comment by wagnerand** [comment]
> Note to myself to upgrade amo-validator requirements to use 3.8.0

@EnTeQuAk I think you meant 3.8.1 as the title of the issue says and the linter uses?

**Comment by EnTeQuAk** [comment]
I totally meant 3.8.1 :laughing:
