### ISSUE TITLE
Raise an error if there's another metadata-file if manifest.json exist

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/amo-validator#420]
We should throw an exception if there's a `install.rdf` or `package.json` once there's a `manifest.json` to make sure we block duplicated metadata early enough.

Tracking: https://github.com/mozilla/addons-server/issues/2450

**Comment by wagnerand** [comment]
Is this still needed now that the linter is active on prod?

**Comment by tofumatt** [comment]
I think no.

- tofumatt

**Comment by EnTeQuAk** [comment]
The question would be wether or not people use amo-validator locally but I guess that's not the case or not enough to work on it I guess
