### ISSUE TITLE
Flag all instances of `unblocker.yt`

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/amo-validator#426]
The domain `unblocker.yt` has been used multiple times by malicious add-ons, so we need to flag all instances of this (in strings) to make sure reviewers reject or escalate those submissions.

CC @wagnerand @eviljeff @kewisch in case anyone wants to take it.

**Comment by tofumatt** [comment]
What has been the nature of the domain usage? Just curious if this is
something we should worry about with WebExtensions as well. (If so I'll
file an issue)

- tofumatt

**Comment by jvillalobos** [comment]
Some of the context is available on [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1251911). While a WebExtension wouldn't be as damaging, it can still do dangerous things if running untrusted code, so I think this flag should be ported to the new linter as well.

**Comment by kewisch** [comment]
If there is a developer-visible validator message that hints towards this, then the developer may just use something non-obvious to circumvent it. Can we make it so it is either only visible to reviewers, or harder to circumvent?

**Comment by andymckay** [comment]
Well this bug and the code is visible already right?

**Comment by kewisch** [comment]
Indeed, finding this issue would surely let them know, but a validator warning is even more prominent than an issue on github :) We can give it a try and see how it goes though.
