### ISSUE TITLE
Raise a warning if not e10s compatible

### ISSUE THREAD

**Issue by andymckay** [mozilla/amo-validator#433]
If an add-on is not e10s compatible as marked by: https://developer.mozilla.org/en-US/Add-ons/Install_Manifests#multiprocessCompatible then raise a warning.

We will likely elevate this to an error at a later date.

Supports: mozilla/addons-server#2770

**Comment by diox** [comment]
@andymckay what should the warning look like ? Do we want to mention a specific Firefox version number in it ?

So far I have come up with this, but I don't like it:
> Your addon is not [marked as compatible with Multi-Process Firefox](https://developer.mozilla.org/en-US/Add-ons/Install_Manifests#multiprocessCompatible) and will not work in future versions of Firefox. Please review it, make changes if needed and set `<em:multiprocessCompatible>` to `true` in `install.rdf` if it's compatible.

Note: the message will need to be slightly more generic to accomodate for jetpack add-ons (which we can't reliably detect, mere presence of `package.json` is not enough). For those, the `multiprocess: true` property in `package.json` must set instead of the one in `install.rdf`.

**Comment by andymckay** [comment]
That's a well written warning. I think we could just add the notes about JPM addons to MDN.

In times like these I ask @wagnerand for advice 😄

**Comment by wagnerand** [comment]
The message looks good. Small nit. `s/will/may/`.

Also, to workaround traditional vs jetpack add-ons differences, we could just link to the respective migration pages on MDN which would be useful either way, as they have testing and migration instructions.

Add-on migration guide: https://developer.mozilla.org/en-US/Add-ons/Working_with_multiprocess_Firefox
SDK based Add-ons and e10s: https://developer.mozilla.org/en-US/Add-ons/SDK/Guides/Multiprocess_Firefox_and_the_SDK

Thoughts?

**Comment by diox** [comment]
I like it, I guess we could have a different link and live with the fact that jetpack detection is unreliable.

One caveat though: these pages mention the property (`<em:multiprocessCompatible>true</em:multiprocessCompatible>` and `multiprocess: true` respectively) but it's a bit hidden in the page. So I think we should still mention them in our message, changing the link but keeping the wording about the property developers need to modify in it. That gives us:

Jetpack extensions:
> Your addon is not marked as [compatible with Multi-Process Firefox](https://developer.mozilla.org/en-US/Add-ons/SDK/Guides/Multiprocess_Firefox_and_the_SDK) and may not work in future versions of Firefox. Please review it, make changes if needed and set the `multiprocess` property to `true` in `package.json` if it's compatible.

Regular extensions:
> Your addon is not marked as [compatible with Multi-Process Firefox](https://developer.mozilla.org/en-US/Add-ons/Working_with_multiprocess_Firefox) and may not work in future versions of Firefox. Please review it, make changes if needed and set `<em:multiprocessCompatible>` to `true` in `install.rdf` if it's compatible.

Random last-minute idea I just had: should we replace "not work" by "break" ?

**Comment by wagnerand** [comment]
lgtm.

I prefer "not work", but I don't really have much of an opinion :)

**Comment by jvillalobos** [comment]
I agree "not work" is better.

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF47(Win 7).
An error is raised for add-ons at validation.
Postfix screenshot: 
![addon-false](https://cloud.githubusercontent.com/assets/15685960/15931977/93de81ac-2e62-11e6-98d2-f34e0a669467.png)

@diox : why is the warning listed twice?
Attaching used add-on.
[ADDON.zip](https://github.com/mozilla/amo-validator/files/307013/ADDON.zip)

**Comment by diox** [comment]
It seems to be the result of your add-on containing a .jar file. The second warning is for that .jar file. It's not a blocker, but it would be nice to fix, can you file a new issue ?

**Comment by ValentinaPC** [comment]
@diox : Thanks and yes.
I'll mark this verified, meanwhile.
