### ISSUE TITLE
Double Multi Process warning if addon contains JAR

### ISSUE THREAD

**Issue by erosman** [mozilla/amo-validator#438]
re: Extension is not marked as compatible with Multi Process
Example:
`https://addons.mozilla.org/en-US/developers/addon/earthweb/file/457094/validation`

> Extension is not marked as compatible with Multi Process
> chrome/Earth.jar/
> 
> Extension is not marked as compatible with Multi Process

**Comment by wagnerand** [comment]
I think that has been fixed by https://github.com/mozilla/amo-validator/pull/437 and will be on prod later this week. Please let us know if it happens again after Thursday.
