### ISSUE TITLE
Info Request attached to the wrong version

### ISSUE THREAD

**Issue by erosman** [mozilla/amo-validator#440]
I rejected an addon. I needed to post additional comments which was done via "Request more information". Previously that was working as it should.

I noticed today that it was attached to the last passed version and not the current but rejected one.

Ref: `https://addons.mozilla.org/en-US/editors/review/klamm-de-websuche-gutscheine`

**Comment by wagnerand** [comment]
This belongs to the `addons-server´ repo.

Anyway it's a regression of `addons-server#9817742ad`.  Info requests are attached to the `latest version_always`. That commit excludes `STATUS_DISABLED` when determining the latest version.

So if we reject a version and send an info-request as a follow-up, the info request gets attached to most recent approved version instead, or worse, if there is none, a pseudo-version `[deleted]` is added and the info request is attached to that.

Adding @eviljeff.

**Comment by wagnerand** [comment]
@eviljeff feel free to re-file this in `addons-server`.

**Comment by wagnerand** [comment]
Or anyone, really.

**Comment by erosman** [comment]
The problem is compounded on the emails sent as outlined in:
https://discourse.mozilla-community.org/t/add-on-is-rejected/9670

The info request (or maybe other emails) details previous version which is confusing for the developer as it was meant for the latest version.
