### ISSUE TITLE
Report deprecation warning for add-ons that use ctypes

### ISSUE THREAD

**Issue by cpeterso** [mozilla/amo-validator#467]
We would like deprecate (and eventually block) add-on access to ctypes. I'm working with bsmedberg to compose a deprecation announcement.

We apparently can't block add-on access to ctypes at run-time (because Firefox uses ctypes itself). @jvillalobos says the AMO validator already flags ctypes add-ons for extra review. bsmedberg would like to expose those warnings to add-on developers and change the wording to mention ctypes deprecation.

https://github.com/mozilla/amo-validator/blob/8efb14ab994a3da419a45191d5c98c42f0203a01/validator/testcases/javascript/predefinedentities.py#L703

https://github.com/mozilla/amo-validator/blob/419852bb5997fac09ae1ca1e1f6247ba49351262/tests/test_js_signing.py#L337

@andymckay

**Comment by wagnerand** [comment]
I think that involves rephrasing the warning text and setting `editors_only` to False.

**Comment by wagnerand** [comment]
@cpeterso 
When would we start deprecating ctypes?
When should we start showing the warning?
What should the warning message be?

**Comment by cpeterso** [comment]
@wagnerand 

We should announce the ctypes deprecation period before we start showing a warning. That will avoid some user confusion and give us a page we can point users to for more information. I'm currently working with bsmedberg to compose the announcement and warning message. I'll keep you posted.

That said, in the meantime, can we just expose the [existing ctypes editors_only warning](https://github.com/mozilla/amo-validator/blob/8efb14ab994a3da419a45191d5c98c42f0203a01/validator/testcases/javascript/predefinedentities.py#L703) to add-on developers without mentioning deprecation yet? Or will exposing that warning confuse add-on developers if we don't have corresponding documentation for the warning?

**Comment by wagnerand** [comment]
Yea, I don't think there is much value to warn developers about their usage of ctypes (without explaining why it raises a warning). The current warning message is really targeted to editors.

**Comment by andymckay** [comment]
This has been announced, and I think we should show this warning and or block now. 

https://blog.mozilla.org/addons/2017/01/24/preventing-add-ons-third-party-software-from-loading-dlls-into-firefox/

/cc @muffinresearch

**Comment by wagnerand** [comment]
I think it makes sense to sync these changes to the announcement. What we're missing is the exact wording though. @cpeterso could you help out with that? @muffinresearch If possible, can we cherry-pick and re-tag for this week's release to reflect the announcement on AMO?

I don't think we should block at this point to give developers some time to adapt their code.

**Comment by muffinresearch** [comment]
@wagnerand we could push that through this week. It sounds like a minimal change if it's just flipping the `editors_only` flag off and updating a string.

For copy could we just use something like (pretty much lifted directly from the blog post text).

```
Starting with Firefox 53, to be released on April 18, Mozilla will introduce changes designed to prevent the loading of third-party binaries into the Firefox process(es). Add-on developers who are currently using JS-ctypes should begin immediately transitioning to the Native Messaging API using WebExtensions (see https://mzl.la/2j4bEwp for documentation and examples). See also https://mzl.la/2joSS11 for the announcement blogpost.
```

**Comment by wagnerand** [comment]
As mentioned in IRC, I think it makes sense to keep it as short as possible.

How about the following? (no code block to improve readability)

_Starting with Firefox 53, to be released on April 18, Firefox will prevent the loading of third-party binaries. If you are currently using JS-ctypes, you should begin immediately transitioning to the Native Messaging API using WebExtensions (see https://mzl.la/2j4bEwp for documentation and examples). See also https://mzl.la/2joSS11 for the announcement blogpost._

**Comment by muffinresearch** [comment]
@wagnerand looks good to me.

**Comment by wagnerand** [comment]
Great, I'll start working on it!

**Comment by cpeterso** [comment]
Thanks! LGTM.
