### ISSUE TITLE
Validator and Highlighter miss .htm files

### ISSUE THREAD

**Issue by erosman** [mozilla/amo-validator#472]
Example:
`https://addons.mozilla.org/en-US/firefox/files/browse/514781/file/popup.htm#top`

Above file is **.htm** and also includes `<script>` tags 
(I am keeping a copy of the addon, in case it gets deleted)

The Syntax Highlighter does not activate on that file.
The validator may be !? working properly since the JS in that file is somehow obfuscated.

**Comment by wagnerand** [comment]
Can you please file bugs under https://github.com/mozilla/addons/ only?

This is the wrong repo for this bug, as the validator handles non-webextensions only.

Thank you.

**Comment by erosman** [comment]
OK... Thanks :)
