### ISSUE TITLE
Bulk validation shows incorrect multiprocessCompatible warning

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/amo-validator#477]
This was reported in [the blog](https://blog.mozilla.org/addons/2016/10/13/compatibility-for-firefox-51/#comment-222860).

See, for example, version 3.0 of [Addons Manager Hilite](https://addons.mozilla.org/addon/addons-manager-hilite/). `install.rdf` has the `multiprocessCompatible` flag set to `true`. The developer page for the add-on shows that it's compatible, and if I upload the file to the [standalone validator](https://addons.mozilla.org/developers/addon/validate) and the [compatibility validator](https://addons.mozilla.org/developers/addon/check-compatibility), neither show any `multiprocessCompatible` warnings. However, the email the developer got points to this [validation result](https://addons.mozilla.org/developers/addon/addons-manager-hilite/validation-result/566186) that does show the incorrect warning. This apparently affected multiple add-ons.

**Comment by wagnerand** [comment]
Wow, this is a tricky one. We skip all `install.rdf` tests for bulk validation due to [bug 735841](https://bugzilla.mozilla.org/show_bug.cgi?id=735841). Collecting manifest data is part of these tests, which sounds odd and I'm surprised this hasn't surfaced sooner.
