### ISSUE TITLE
AMO Validation does not work correctly when `async / await` are used.

### ISSUE THREAD

**Issue by asamuzaK** [mozilla/amo-validator#484]
I've got `JavaScript Compile-Time Error` warnings when I uploaded my add-on to AMO.
2 types of messages.

> A compile-time error in the JavaScript halted validation of that file.
> 
> Message: missing ; before statement

> A compile-time error in the JavaScript halted validation of that file.
> 
> Message: invalid arrow-function arguments (parentheses around the arrow-function may help)

All of my JS files are warned, and I use async / await in them.

My source and warnings.
https://addons.mozilla.org/en-US/firefox/files/browse/537463/

PS I'm also noticed about <em:hasEmbeddedWebExtension>.

**Comment by wagnerand** [comment]
Hey, thanks for the report, I was already thinking about that.

async/await are in Nightly only, right?

**Comment by asamuzaK** [comment]
Now Dev Edition too.

**Comment by wagnerand** [comment]
Thanks!
