### ISSUE TITLE
No install.rdf or manifest.json found

### ISSUE THREAD

**Issue by ritikakh** [mozilla/amo-validator#485]
Hi Mozilla Members,

I am facing this error while I try to upload my zip and xpi files. I have tried to search a lot, couldn't find much that could help me. Any kind of help would be appreciated.

Thanks
[imgHndlExtension.zip](https://github.com/mozilla/amo-validator/files/593421/imgHndlExtension.zip)

**Comment by andymckay** [comment]
The `install.rdf` needs to be in the root of your zip file. Currently its `imgHndlExtension/install.rdf`.

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Publishing_your_WebExtension#1._Zip_up_your_add-on%27s_files
