### ISSUE TITLE
[fx52] Show compatibility error if an add-on uses mozDash or mozDashOffset

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/amo-validator#492]
As part of [bug 931389](https://bugzilla.mozilla.org/show_bug.cgi?id=931389), `mozDash` and `mozDashOffset` are no longer supported. All instances of these properties should be flagged.

This is a compatibility error, so the add-on shouldn't be upgraded in this case. It should also appear as a warning in regular validations.

Message:

The mozDash and mozDashOffset properties are no longer supported. You can use [setLineDash()](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/setLineDash) instead.

Affected add-on: https://addons.mozilla.org/addon/zotfile/

Release timing: Firefox 52 will be released on March 7th.

**Comment by EnTeQuAk** [comment]
Since we don't have a "in progress" label, I started working on this. Should be ready shortly
