### ISSUE TITLE
[fx52] Show compatibility warning if an add-on uses nsISupportsArray

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/amo-validator#493]
As part of [bug 792209](https://bugzilla.mozilla.org/show_bug.cgi?id=792209), `nsISupportsArray` is being deprecated. All instances of this interface should be flagged.

This is a compatibility warning, so the add-on should still be upgraded in this case. It should also appear as a warning in regular validations.

Message:

The nsISupportsArray interface is deprecated and is being replaced by nsIArray. See [this bug report](https://bugzilla.mozilla.org/show_bug.cgi?id=792209) for more information.

Affected add-on: https://addons.mozilla.org/addon/pagesaver/

Release timing: Firefox 52 will be released on March 7th.

**Comment by EnTeQuAk** [comment]
Since we don't have a "in progress" label, I started working on this. Should be ready shortly
