### ISSUE TITLE
Flag any reference to XPIProvider as a high severity signing warning

### ISSUE THREAD

**Issue by EnTeQuAk** [mozilla/amo-validator#500]
XPIProvider is a private interface which add-ons should not be allowed to access. We need to flag any reference to either the symbol or the name. See bug https://bugzilla.mozilla.org/show_bug.cgi?id=1200929 for more.

Originally https://github.com/mozilla/addons-linter/issues/211, it's better here where it needs to be for legacy addon support.

**Comment by wagnerand** [comment]
I think we can close this since _signing_severity_ is no longer relevant and we already raise a warning in https://github.com/wagnerand/amo-validator/blob/b9b2af58c46de7dfb905c1255a53dfdd8b3dd520/validator/testcases/regex.py#L278
