### ISSUE TITLE
Validation of XPI with SDK is not stable.

### ISSUE THREAD

**Issue by liuyuns** [mozilla/amo-validator#501]
With the same code base, the result differs, and there is a high chance to fail. Please review the results below:

passed one
https://addons.mozilla.org/en-US/developers/addon/hpe-functional-testing-agent/file/597828/validation

failed one
https://addons.mozilla.org/en-US/developers/upload/504e72cab45e4db3925ade37da7f9e04

**Comment by wagnerand** [comment]
Thank you for your report.

The second link is 404.

**Comment by liuyuns** [comment]
Update the links in the original post. Sorry for inconvenience. Please help check again.

**Comment by wagnerand** [comment]
Thank you for the update.

Could you also please provide the file you uploaded and a link to your add-on on AMO? If it's unlisted, a link to your developer hub is fine too.

Thanks.

**Comment by liuyuns** [comment]
Here is the link to my developer hub (yes, it is unlisted) 
https://addons.mozilla.org/en-US/developers/addon/hpe-functional-testing-agent

And the file
[Agent.zip](https://github.com/mozilla/amo-validator/files/806463/Agent.zip)

**Comment by wagnerand** [comment]
I compared the file of the first validation report (https://addons.mozilla.org/en-US/developers/addon/hpe-functional-testing-agent/versions/2044895) to the file you attached to this issue and they are very much different.

**Comment by liuyuns** [comment]
Few days ago (back to when I posted on the forum) it is still the same. The one attached is from today. 
Recently we add WebExtensions for our extension with same code base, but in WebExtensions. And both shared the same ID. 
The failure happens frequently since then. 
In the past we can still get 1 or 2 pass after 10 failures or so. But these days it is just keep failing. 

If I build the extension with a different ID, it just pass. But this is not good for us since we need the same ID as before. 

Any suggestions we can take?

**Comment by wagnerand** [comment]
I am sorry I don't follow. The file you attached is not a webextension. And version 14.1.2245.0 is different from the file you attached, so they might produce different validation results.

**Comment by liuyuns** [comment]
Sorry for complexity. The one I attached is SDK. 
Now we have both SDK and WebExtension with same ID. The WebExtension can pass while the SDK cannot. 

Before we moved to WebExtension, the SDK pass the sign very smoothly. 

Besides, if I built the SDK with a different ID, it can pass the sign as well; But with the current ID it fails constantly now.

**Comment by wagnerand** [comment]
Can you please attach the correct file so we can test and reproduce?

**Comment by liuyuns** [comment]
Please try this one - 2246 

[Agent.zip](https://github.com/mozilla/amo-validator/files/806608/Agent.zip)

**Comment by wagnerand** [comment]
That file is not a webextension, it's still an SDK file.

**Comment by liuyuns** [comment]
That is exactly the problem. We must also sign the SDK file!

**Comment by wagnerand** [comment]
This file validates just fine for me.

<img width="982" alt="screen shot 2017-02-28 at 13 51 27" src="https://cloud.githubusercontent.com/assets/873258/23405984/0ff9060c-fdbd-11e6-8172-a64b37aa94fa.png">

**Comment by liuyuns** [comment]
Would you please open the full validation report? I got "Add-on **failed** validation."

And "There was an error with your upload. Please try again" if proceed to sign. 

Here is my validation result:
https://addons.mozilla.org/en-US/developers/upload/742e6918d98b4467a8d33e3667873cbc

**Comment by wagnerand** [comment]
I see

<img width="983" alt="screen shot 2017-02-28 at 14 02 02" src="https://cloud.githubusercontent.com/assets/873258/23406298/84355d62-fdbe-11e6-83fd-4d8cc1c357b3.png">

Looking at your validation result, I don't see any reasons why this add-on would fail validation.

I am not sure what to do here since I cannot reproduce the issue.

**Comment by liuyuns** [comment]
This is too bad. Your result is what we need, **passed** with warnings (we used to have such kind of result for years). 
But now we can only get **failed**. 
Where would you please redirect me for help? 

Besides, why it passes if I change the extension ID?

**Comment by wagnerand** [comment]
@EnTeQuAk any ideas here?

**Comment by liuyuns** [comment]
More information. I tried following:
1. Remove all codes, make it an almost empty extension with same ID. 
2. Upload and still **failed** with "**You cannot update a WebExtensions add-on with a legacy add-on. Your users would not be able to use your new version because Firefox does not support this type of update**." **Is this the cause**?

Please note we uploaded WebExtension version with the same ID before, back to then SDK could be signed for a while. 
Now the validation seems more **restricted**. I verified with the passed result there is no such warning.

Would you please help from here?

**Comment by wagnerand** [comment]
I just submitted the file attached in https://github.com/mozilla/amo-validator/issues/501#issuecomment-283016726 to your add-on and it worked just fine.

![screen shot 2017-03-01 at 11 50 17](https://cloud.githubusercontent.com/assets/873258/23456834/5af0c484-fe75-11e6-880b-a21d8c55e773.png)

**Comment by liuyuns** [comment]
Would you please review my last comment again? And please check snapshot below. 

Although it says the addon can be signed automatically, but the truth is it cannot!
 
![image](https://cloud.githubusercontent.com/assets/1592774/23457119/7871b554-feb1-11e6-9346-853d4e7361e4.png)

**Comment by wagnerand** [comment]
That is a warning only. It would be an error for listed add-ons only, which your add-on is not.

**Comment by liuyuns** [comment]
Thank you. So how can we explain the failure by signing? 
I am submitting via this link:
https://addons.mozilla.org/en-US/developers/addon/hpe-functional-testing-agent/versions/submit/

Once I click **'Sign Add-on**' after validation, I can only get following:
"There was an error with your upload. Please try again."

Please we need help! Should I open the issue to any other place?

**Comment by wagnerand** [comment]
You keep sending us different error messages, which makes debugging this issue very hard. I might have found a bug which could cause one of things you see, but I need to talk to other engineers about it to confirm.

**Comment by liuyuns** [comment]
I am trying to offer  more information since you couldn't reproduce. 
Sorry if those troubles you. All I need is to pass sign! 
To brief the 2 error messages:
"Add-on failed validation" (inside there is the warning about cannot upgrade WebExtensions  with SDK) -> "There was an error with your upload. Please try again" (when proceed to Sign Add-on).

Please kindly let me how the bug goes.

**Comment by wagnerand** [comment]
Thank you for your help, I was finally able to reproduce it. I filed https://github.com/mozilla/addons-server/issues/4810

**Comment by wagnerand** [comment]
The issue has been fixed and will be deployed to our servers on Thursday. Can you please try again on Friday? Thank you.

**Comment by liuyuns** [comment]
Thank you Andreas! Really appreciate :+1: 
Yes, we will try it on Friday.

**Comment by liuyuns** [comment]
Awesome! It is signed successfully now (noticed from our routine build result) :+1: 
Thanks again!
