### ISSUE TITLE
[fx56] Show compatibility error if an add-on uses `showModalDialog`

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/amo-validator#557]
As part of [bug 981796](https://bugzilla.mozilla.org/show_bug.cgi?id=981796), `window.showModalDialog` has been removed. All instances of this function should be flagged.

This is a compatibility error, so the add-on shouldn't be upgraded in this case. It should also appear as a warning in regular validations.

Message:

The showModalDialog function has been removed. See [this bug report](https://bugzilla.mozilla.org/show_bug.cgi?id=981796) for more information.

Affected add-on: https://addons.mozilla.org/addon/imtranslator/

**Comment by jvillalobos** [comment]
This may be the last compat bug filed for this validator 🕺🏼🕺🏼🕺🏼

**Comment by andymckay** [comment]
🎉 👍

**Comment by wagnerand** [comment]
@EnTeQuAk fyi, this needs to land before Aug 1.

**Comment by EnTeQuAk** [comment]
I'm currently working on it and plan to land it next week

**Comment by wagnerand** [comment]
No rush, just wanted to set expectations :)

**Comment by wagnerand** [comment]
@jvillalobos I ran the bulk validation and the affected add-on does not show up. I had a look at the code and couldn't find any reference to `showModalDialog` for the last two recent versions, leading back to December 2016.

**Comment by jvillalobos** [comment]
I get those samples from DXR, but maybe I messed something up, and DXR seems to be down now. If you can see add-ons correctly flagged in the results of the run, I think this is okay to go.
