### ISSUE TITLE
Validator is missing issues 2

### ISSUE THREAD

**Issue by erosman** [mozilla/amo-validator#566]
ref: `https://addons.mozilla.org/editors/review/843980/`

Today I noticed that the following showed all passed (zero warnings)

`https://addons.mozilla.org/en-US/developers/addon/whaleslide_v1/file/702610/validation`

However there are multitude of issues that it should have listed.

Previously: #370 #461

**Comment by wagnerand** [comment]
Could you tell us what issues exactly have been missed/what issues you expected to be there? Thanks!

**Comment by erosman** [comment]
Addons has 39 JS files including an unrecognised JQuery which usually attracts a lot of warning (createElement("script"), innerHTMl etc).

**Comment by wagnerand** [comment]
Ah, this is a webextension, so this goes to https://github.com/mozilla/addons-linter

Also, we really need to know what **exact** issues are not flagged. The fact that there are 29 JS files does not say anything about which or how many warnings should be shown, if any at all.

**Comment by erosman** [comment]
I mixed up the linter and non-linter :p
