### ISSUE TITLE
Add libraries to hashes-allowed?

### ISSUE THREAD

**Issue by bbernhard** [mozilla/amo-validator#583]
Hi,

I recently pushed my Firefox extension to the Mozilla app store, but after a few days it got deactivated with `Your add-on includes a JavaScript library file that doesn't match any versions known to us. We require all add-ons to use unmodified release versions.`

As I am using `Semantic UI` (and some other less known javascript libraries)  which are not listed in https://github.com/mozilla/amo-validator/blob/master/validator/testcases/hashes-allowed.txt I wanted to ask if it's possible to add those to the `hashes-allowed.txt` list? Are there some guidlines which javascript libraries are allowed in there? Do you manually review each library before it gets added to the list? 

Thanks,
Bernhard

**Comment by wagnerand** [comment]
The review message was most probably not about that file. Reviewers are supposed to send out that note only for well known libraries like jQuery. Please get back to your reviewer asking which file/library this is about.

Also, the URL you linked to is used for legacy add-ons only, so don't expect any updates to it.
