### ISSUE TITLE
Does it have (or will have) the same functionality as the online validator?

### ISSUE THREAD

**Issue by arieljannai** [mozilla/amo-validator#591]
In the past, I was using the [addon validator](https://addons.mozilla.org/en-US/developers/addon/validate)* to validate my xpi files.

**Does this repo is the cli tool to support to same functionality?**

_I currently don't have any xpi to test (previous job). The last time I needed it was two years ago, and I wanted to know if somethings has changed for the next time I'll need it (at the time, I was looking for a cli tool but there wasn't anything available)._

*Maybe it's not that link anymore, but it was two years ago.

Thanks!

**Comment by diox** [comment]
Hi,

Please use https://github.com/mozilla/addons-linter instead now.
